### PR TITLE
Choc Spacing

### LINKED ISSUE #2: Version with choc spacing
It would be interesting to also have an alternative version with choc spacing now that keycaps supporting it are becoming more and more common. Call it something like KeyBeeSee Compact?

### PR DESCRIPTION
**Pull request by ibnuda**
it uses choc spacing. it should close #2.

### CODE REVIEW

**Comment by TeXitoi** [comment]
Ho, great!

I'll try to look at it. What I'll look (more for me as a reminder):
 - choc only switch footprints?
 - 17x18mm spacing?
 - correct spacing of key, the thumbs are offset by 0.5u (so 9mm?)
 - are the key placement of the 2 side symmetric (that's a bit wrong in v0.2)

**Comment by ibnuda** [comment]
1. yes. choc only footprint.
2. yes. the footprint is 18mm wide and 17mm tall.
3. yes, the thumbs are offset by 9mm.
4. yes, symmetric, as far as i can tell.

**Comment by TeXitoi** [comment]
First, sorry to have taken so much time to review this.

I'm sorry, but I finally don't want to have these in this repository. I don't want to take the responsibility of them, and I prefer to have a unique official version with choc and mx compatibility.

I'd happily link to a repo with these PCB. They can keep the KeySeeBee name, or change the name, or add some postfix. You can do whatever you want with the `by TeXitoi`: remove it, keep it, add your name, change it with your name.

Now, a few remarks about the PCB (a review, with personal remarks, taking them or not into account is not required for me adding a link to them).

The cut outline is supposed to pass exactly at the angles of the switch footprint spacing. That's near but not exactly on it to most, but that's clearly not the case at the top. It should be easily fixable (by using a millimeter grid).

I think the switch placement is not perfect: we can see that the outline of the switch doesn't match exactly from one to another. Using a millimeter grid, you can easily have a perfect match.

The angle of the extreme thumb switch was calculated to correspond to the triangle formed by the surrounding switches. As choc spacing is not square, the angle doesn't match anymore. It can thus be ajusted to `arctan(9/17) ≈ 27.9°`.

The cutout outline around the extreme thumb switch is supposed to be tangential to the switch outline.

There is some diodes under the outline of the extreme thumb. I think there must be no components under the outline of the switches. It will allow to use a plate.

The top cut outline, where the connectors are, is not aligned with the first switch. But, to do this alignment, the components would need to be rearranged, and that's a lot of work. I think it is OK if this outline is between the top of the first column, and the top of the highest column. I've checked, and it's doable, even by moving everything up to not have any component under the switch outlines.

Thanks for the contribution!

**Comment by ibnuda** [comment]
not a problem, chief.😎

**Pull request closed without merging**
